type Query {
    books: [Book]
    bookById(id: Int): Book
    articles: [Article!]!
    article(id: ID!): Article
}

type Mutation {
    createArticle(input: CreateArticleInput!): Article!
    addComment(articleId: ID!, input: AddCommentInput!): Comment
}

type Book {
    id: ID
    name: String
    pageCount: Int
    author: Author
}

type Author {
    id: ID
    name: String
}

input CreateArticleInput {
    title: String!
    content: String!
    userId: ID!
}

input AddCommentInput {
    userId: String!
    content: String!
}

type User {
    id: ID!
    name: String!
}

type Article {
    id: ID!
    title: String!
    content: String!
    author: User!
    comments: [Comment!]!
    createdAt: String!
}

type Comment {
    id: ID!
    content: String!
    author: User!
}
